version: '3.3'

services:
  traefik:
    image: 'traefik:v2.4'
    container_name: 'traefik'
    restart: unless-stopped
    command:
      - '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.myresolver.acme.httpchallenge=true'
      - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web'
      - '--certificatesresolvers.myresolver.acme.email=codememory101@gmail.com'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '443:443'
      - '80:80'
      - '8080:8080'
    volumes:
      - '/root/letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - app-network

  node-server:
    build: .
    container_name: node-server
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - app-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.node-server.rule=Host(`stockgeniejm-api-dokdmlhsoq-rc.codememory.xyz`, `67.205.134.94`)'
      - 'traefik.http.routers.node-server.entrypoints=websecure'
      - 'traefik.http.routers.node-server.tls.certresolver=myresolver'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.redirs.entrypoints=web'
      - 'traefik.http.routers.redirs.middlewares=redirect-to-https'
    volumes:
      - '/root/logs:/usr/src/app/logs/'
networks:
  app-network:
    driver: bridge
